add Notice component
pinglue/site pull request #19
Opened 2022-01-12 00:25 UTC by aminsaedi

2022-01-12 04:45 UTC, pmvald requested changes

2022-01-12 04:45 UTC, pmvald commented on docs-src/pgweb/01-topic.mdx
> +<Notice>Notice Two</Notice>
This work if the content is raw text. I my new commit I added some mdx syntax inside the tag. See how you can make the interior mdx render (just like the outside look sample I made under the notice box) hint: may be Notice children have to be wrapped by some mdx component or so?

2022-01-12 04:45 UTC, pmvald commented on src/components/notice/notice.tsx
> +const Notice = ({ children, type }: { children: any; type?: string }) => {
Better to use function instead of arrow function for the main export of the page/component (arrow function is supposed to be brief syntax to be used mainly for inline callbacks, like map, filter, etc)

```
export default function({ children, type }: ...)
```

2022-01-12 21:52 UTC, aminsaedi commented on docs-src/pgweb/01-topic.mdx
> +<Notice>Notice Two</Notice>
I added another lib to render nested md content, because it is not possible to use nested `<MDXRenderer>` component

2022-01-13 01:26 UTC, pmvald commented on docs-src/pgweb/01-topic.mdx
> +<Notice>Notice Two</Notice>
Sounds good, did you commit it here? I don't see any commit here

2022-01-13 04:19 UTC, pmvald approved these changes
Looks good. Now that we use the same npm version you can include your package-lock.json - it is ok to change this file when you install a new package (it has to be changed)

One question: we already have two mdx packages installed: "@mdx-js/mdx" and "@mdx-js/react" - do they not have any method to convert md or mdx to jsx (instead of using markdown-to-jsx package) ? If not, then it is ok

2022-01-13 04:20 UTC, merged

2022-01-13 16:07 UTC, aminsaedi commented
Sure, I'll add lock file in new branches

I tried both but non of them works. this is why I add new package