enhancement/global-state
pinglue/site pull request #39
Opened 2022-01-21 02:41 UTC by aminsaedi

2022-01-22 02:05 UTC, pmvald requested changes

2022-01-22 02:05 UTC, pmvald commented on src/store/doc.ts
> +  activeTabId: string;
we need another layer for tabId, so the doc structure is something like

```
{
activeTabIndices: {
   [tabId]: string (activeTabIndex)
}
}
```

2022-01-22 02:05 UTC, pmvald commented on docs-src/pgweb/01-topic.mdx
> +<Tab id="javaScript" label="Java-Script">
no need for this change

2022-01-22 02:07 UTC, aminsaedi commented
This commit is before youe mention. I know it problems. I'm working on it

2022-01-22 02:09 UTC, aminsaedi commented
a question
how can I filter this query based on `previous.base` I want `previous.base` to be `docs-src` to get list of root folders (`pwgeb` and `pingule`)
```
query MyQuery {
  allDirectory {
    edges {
      previous {
        base
      }
      node {
        relativePath
        base
        absolutePath
      }
    }
  }
}

```

2022-01-22 02:40 UTC, pmvald commented
> a question how can I filter this query based on `previous.base` I want `previous.base` to be `docs-src` to get list of root folders (`pwgeb` and `pingule`)
> 
> ```
> query MyQuery {
>   allDirectory {
>     edges {
>       previous {
>         base
>       }
>       node {
>         relativePath
>         base
>         absolutePath
>       }
>     }
>   }
> }
> ```

For what purpose you need a list of doc names? ...

2022-01-22 03:50 UTC, aminsaedi commented
> > a question how can I filter this query based on `previous.base` I want `previous.base` to be `docs-src` to get list of root folders (`pwgeb` and `pingule`)
> > ```
> > query MyQuery {
> >   allDirectory {
> >     edges {
> >       previous {
> >         base
> >       }
> >       node {
> >         relativePath
> >         base
> >         absolutePath
> >       }
> >     }
> >   }
> > }
> > ```
> 
> For what purpose you need a list of doc names? ...

I wanted to store tab status of each doc in the redux store.
Please look at ne commit
in this new store structure we can store state of each doc separately.
but it has an issue: each time we add new folder to `docs-src` we have to modify `doc.ts` file. (maybe it's not a problem because usually we do not add new folder to  `docs-src`)

2022-01-22 03:55 UTC, aminsaedi commented
about the `activeDoc` in `doc` slice of store.
I added this because I need to know which doc is on screen in order to add new tab
there was two ways: 1- add new prop to `TabContainer` component and pass doc name there 2- save active doc in the store and read it from store in `tabs.tsx`
I thought the second approach is more cleaner. I can use another way if you think it's not a good idea

2022-01-22 17:57 UTC, pmvald commented
Yes we should hardcode doc names into the store. Gatsby graph ql cannot be used for that, it is only available for generating react components at build; so you can use graph ql only inside components or hooks - not anywhere else

redux is a temporary solution - soon we will replace it with our Pinglue system which will do the same thing way easier, without all these classes and boilerplates ...

2022-01-22 18:25 UTC, pmvald approved these changes
Looks good - please resolve the discussions and merge (you might need to do conflict resolution though)

2022-01-22 18:25 UTC, pmvald commented on src/components/doc-page.tsx
> +    dispatch(changeActiveDoc(slug.split("/")[0]));
Make an issue: "making slug as context for doc-page component"

In addition to this task, we need slug in several other sub components (like header for generating the breadcrumb)

We will do this later

2022-01-22 18:25 UTC, pmvald commented on src/store/doc.ts
> +}
Also count how many new lines of code we added in order to add the redux feature - later we compare it with our own tools and see simplification

2022-01-23 13:26 UTC, aminsaedi commented
> Looks good - please resolve the discussions and merge (you might need to do conflict resolution though)

I don't have write access to the repo so I can't resolve file confilicts
<img width="828" alt="image" src="https://user-images.githubusercontent.com/23167933/150680676-20873fb9-107c-447a-b155-d094ca12bb39.png">

2022-01-23 16:15 UTC, pmvald commented
> > Looks good - please resolve the discussions and merge (you might need to do conflict resolution though)
> 
> I don't have write access to the repo so I can't resolve file confilicts <img alt="image" width="828" src="https://user-images.githubusercontent.com/23167933/150680676-20873fb9-107c-447a-b155-d094ca12bb39.png">

Basically what you have to do first is to resolve the conflicts which is done within your own branch:

```
git fetch // update
git checkout main
git pull // update main
git checkout your-branch // go to your branch
git pull // update your branch
git merge main // merge latest changes from main
```

After this you will see some errors saying there are conflict with main - those conflicting line will be marked by a certain notation called "conflict marker" (lot of ">>>>>>>>>>>>>>>>>>") and those files containing conflict will not merge (you can run `git status` and see the unmerged files) - now editors like VSCode can recognize these conflict markers and help you resolve them by deciding what should be final value of those lines. When you resolve all conflicts save the file(s) and stage all the unmerged files:

```
git add .
```

Now commit and push to your branch - Now when you come to this page again you will see that the message "This branch has conflicts that must be resolved" on the merge button is gone and it says "no conflict" - at this stage all we need to do is to press the merge button to merge (choose the "squash and merge" option) - At this stage you may not have actually permission to do the merge. We have to check this, what I wanted to do is to give merge permission to anyone provided that the PR is approved by an admin, but I may not have done this correctly so maybe I'm the only one with merge permission. If that happens let me know and we will figure it out.

Now try to do the conflict resolution first

2022-01-23 16:17 UTC, pmvald commented
But for this PR let me do the conflict resolution because there were some other changes in other branches and it may not be clear to you which option to choose when resolving conflicts ... but keep the previous comment in mind and at some point you will be practice it to learn how to resolve conflicts in git

2022-01-23 16:38 UTC, merged