Basic footer for doc-page - 10%
pinglue/site pull request #54
Opened 2022-01-23 07:30 UTC by yuki-tylar

Fixes #21

2022-01-23 17:42 UTC, pmvald commented
Good! When you finish your PR use the review button the right to "request review" - this way we know that this PR is done and ready to review ... so, is this PR ready?

2022-01-23 17:43 UTC, pmvald requested changes

2022-01-23 17:43 UTC, pmvald commented on src/pages/__mocks/doc-page-res.tsx
> +			<div className="py-hq px-2 text-center" style={{backgroundColor: '#0d1117', color: '#e5e5e5', fontWeight: 300, fontSize: '14px'}}>
class `ss-doc-footer` maybe?

2022-01-23 18:26 UTC, yuki-tylar commented
Yes it's ready to merge :) 

Sorry I can't find `review button the right to "request review"`. Could you please tell me where it is?

2022-01-24 02:40 UTC, pmvald commented
I think you should "re-request review" - using the icon that is similar to refresh icon ...

2022-01-24 02:40 UTC, pmvald commented
I think you should "re-request review" - using the icon that is similar to refresh icon ...

2022-01-24 19:02 UTC, yuki-tylar commented
I tried re-request. I hope it works :)

2022-01-24 20:43 UTC, pmvald commented
Yes it did! I'll review it soon

Sent from Yahoo Mail on Android 
 
  On Mon., 24 Jan. 2022 at 2:03 p.m., ***@***.***> wrote:   


I tried re-request. I hope it works :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>

2022-01-25 04:09 UTC, pmvald approved these changes

2022-01-25 04:13 UTC, merged