Mobile view touchups - 10%
pinglue/site pull request #59
Opened 2022-01-25 05:51 UTC by yuki-tylar

Fixes #49

2022-01-26 14:38 UTC, pmvald requested changes

2022-01-26 14:38 UTC, pmvald commented on src/components/header/header.tsx
> +	let path = window.location.pathname.replace(/^\/|\/$/g, '').split('/');
Please create a bug issue refering to this line, later we need to replace this with the slug that's coming from the context (useContext) rather than window url.

2022-01-26 14:38 UTC, pmvald commented on src/components/header/header.tsx
> -				<a>
github icon has to be hidden only in mobile view, not completely

2022-01-26 14:38 UTC, pmvald commented on src/components/header/header.tsx
> +					<span className="d-none d-md-inline me-q">Edit this page</span>
this has to be moved on the right side of the nav -

2022-01-26 14:38 UTC, pmvald commented on src/components/header/header.tsx
> +				<a className="ms-1h px-h py-q" style={{fontSize: '13px'}}>
we have a class; s-text-sm or similar for altering text sizes, it should be in _styles/utils (check sss repo)

2022-01-26 17:02 UTC, yuki-tylar commented on src/components/header/header.tsx
> +	let path = window.location.pathname.replace(/^\/|\/$/g, '').split('/');
I could not create new issue.
It seems I have no authority?

2022-01-28 13:58 UTC, pmvald commented on src/components/header/header.tsx
> +	let path = window.location.pathname.replace(/^\/|\/$/g, '').split('/');
Really? that's not possible, everybody should be able to create issue, even people who are not part of the org or repo. let me double check

2022-01-28 14:04 UTC, pmvald approved these changes

2022-01-28 14:05 UTC, merged

2022-01-28 16:39 UTC, yuki-tylar commented on src/components/header/header.tsx
> +	let path = window.location.pathname.replace(/^\/|\/$/g, '').split('/');
Ohh... I'm sorry. I was trying to add new Todo on project.
I created new issue about this. sorry for confusing.