enhancement/doc-cross-link
pinglue/site pull request #60
Opened 2022-01-25 06:20 UTC by aminsaedi

2022-01-26 14:52 UTC, pmvald requested changes

2022-01-26 14:52 UTC, pmvald commented on src/components/appLink/appLink.tsx
> +    const slug = data.allMdx.nodes.find((i) => i.id === to.substring(1)).slug;
`i.id` should be replaced by something like `i.frontmatter.id` - the catch is mdxAll does not return the id of the front matter, maybe we should try another endpoint ...

2022-01-26 14:52 UTC, pmvald commented on docs-src/pgweb/02-topic.mdx
> +<AppLink to=":272119aa-5dc6-5c4b-9f48-a77b2314bcb5" >
this is good to begin with.  Now note that this id is generated by gatsby at build time (and could be even different for each build)  so we cannot use it as part of our doc. The id here should be defined in the doc frontmatter:

```
---
title: Article title
id: my-simple-id
---
```

then we use `<AppLink to=":my-simple-id" >`

2022-01-26 14:52 UTC, pmvald commented on src/components/doc-page.tsx
> +const SHORTCODES = { Warn, Prereq, Recall, Tip, Note, Tab, TabContainer,AppLink, h2: H2, h3: H3 };
see if you can make mdx replace its regular link notation with AppLink, so that:

`[link name](:my-simple-id)` --> `<AppLink to=":my-simple-id"> link name </AppLink>`

Note that the md expression `[link name](:my-simple-id)` is converted to `<a>` at the end, so maybe adding something like `a: AppLink` to shortcodes should work (you just have to map href prop to to prop)

2022-01-27 03:54 UTC, aminsaedi commented on src/components/appLink/appLink.tsx
> +    const slug = data.allMdx.nodes.find((i) => i.id === to.substring(1)).slug;
I added 
```
---
title: Topic 2
id: my-simple-id-two
---
```
to `pgweb/02-topic` and use this query to get slug
```
query {
        allMdx {
          nodes {
            slug
            frontmatter {
              title
              id
            }
          }
        }
      }
```

I think there is no need to add a plugin

2022-01-28 14:20 UTC, pmvald approved these changes

2022-01-28 14:20 UTC, pmvald commented on src/components/appLink/appLink.tsx
> +    const data = useStaticQuery(graphql`
FYI: hooks call (useFuncions) should not be conditioned, they must be called in the component root. Why? because hooks are handled by the order in which they called. This order should be the "SAME" throughout all renders of the component. If you make condition on hook calls, and conditions become different in a component render, then the order of hook calls will not be the same as before and the hooks return wrong results.

2022-01-28 14:20 UTC, pmvald commented on src/components/appLink/appLink.tsx
> +    const slug = data.allMdx.nodes.find((i) => i.frontmatter?.id === href.substring(1))?.slug;
Create a bug to optimize this part by "creating a hook to return toc in a nice format to be used in multiple places"

2022-01-28 14:20 UTC, merged