chnages html sementic tag in headerlist
pinglue/site pull request #70
Opened 2022-01-29 14:36 UTC by AjRadwan

**Changes div to** 

_aside > ul >  li_ 

This fixes #69

2022-01-29 21:36 UTC, pmvald requested changes

2022-01-29 21:36 UTC, pmvald commented on src/components/headersList/headersList.tsx
>  					<div className="my-1">
replace this with `<li className="my-1">`

2022-01-29 21:36 UTC, pmvald commented on src/components/headersList/headersList.tsx
> +						<li><a href={"#" + paramCase(i.value)} >
see above

2022-01-29 21:36 UTC, pmvald commented on src/components/headersList/headersList.tsx
>  								<div className="ms-h my-h">
same as above, replace this div with li

2022-01-30 02:46 UTC, AjRadwan commented on src/components/headersList/headersList.tsx
>  								<div className="ms-h my-h">
I changed it according to what you told me.  I hope this works fine now

2022-01-30 04:39 UTC, pmvald approved these changes

2022-01-30 04:39 UTC, merged