feat: adding cli doc (generated from its yaml file) 50%
pinglue/site pull request #80
Opened 2022-02-13 19:02 UTC by yuki-tylar

Fixes #78

2022-02-13 19:04 UTC, yuki-tylar commented
followed Gatsby's design.

* I added examples in yaml file.
* Currently, I'm using doc-page-res as mock

2022-02-13 21:13 UTC, pmvald requested changes
looks good. I made some comments

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/cli-doc.tsx
> +			<h1>Commands (pinglue CLI)</h1>
everything here should move to a component (within components folder) called `cli-doc` with a data prop (and type `Prop` as you defined here). Then you can import it in this mock page and display it.

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/cli-doc.tsx
> +	const commandName = (s: string) => {
utility functions are better to be defined outside of the component function. This way they get compiled just once

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/cli-doc.tsx
> +			<h1>Commands (pinglue CLI)</h1>
We also need a section on the top for the main cli as well. Its format is the same as individual commands, but it info come from the top level fields in the yaml file: `description`, `command` (this last one I just added in a new commit). And then we show a table or list of the commands with the same format that is used for flags: we show the command usage (command field) of each command along with the command description. For command description, I think itis good we have a new field `shortDescription` that we use in this table. I added such a field for the first command. If a command does not have shortDescription then we fall back to its description. AFter this section we show section for individual fields starting with `<h2>CLI commands </h2>` (each command section begins with its name in `h3` as you already did)

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/cli-doc.tsx
> +						<table className="table">
The problem with table is it doesn't show well in mobile ... what does the Gatsby website do in mobile view? Maybe we use responsive columns here where the description falls under the flag in mobile view. See what is the best way

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/cli-doc.tsx
> +								<h4>Examples</h4>
+1 for examples

2022-02-13 21:13 UTC, pmvald commented on src/pages/__mocks/doc-page-res.tsx
>  import { Helmet } from 'react-helmet';
we can just create a new mock page to show cli doc. Why destroying this one? this mock could still be needed for testing more demos.

2022-02-15 07:08 UTC, yuki-tylar commented
Updated.

* brought back `DocPageRes`
* copied `DocPageRes` into `CliDoc` in `__mocks` instead of modifying original `DocPageRes` . `CliDoc` in `__mocks` use `CliDocBody`
* created `CliDocBody` in `component` folder. This is contentBody in `<article class=s-content'></article>`
* created `CliDocItem`. this is reusable command section
* table is now responsive.

2022-02-15 16:01 UTC, merged